import {
  GeneralInformationSection,
  ProgramSelectionSection,
  ProgramSpecificQuestionsSection,
  QualifyingQuestionsSection,
} from "@/types/EnrollmentForm";

export const generalInformationSectionDefaultValues: GeneralInformationSection =
  {
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    confirmPassword: "",
    dateOfBirth: "",
    sex: "male",
    phoneNumber: "",
    address: "",
    preferredMethodOfContact: "phone",
    isUsCitizen: true,
    hasClassACdl: true,
    cdlNumber: "",
    truckingIndustryAffiliation: "driver",
    jobDescription: "OTR Driver, away 4+ nights a week",
    referralSource: "",
    employer: {
      name: "",
      contact: "",
    },
    doctors: [],
    monthlyHouseholdExpenses: 0,
    isOwnerOperator: false,
    ownerOperatorInfo: {
      businessIncome: 0,
      businessExpenses: 0,
    },
    hasAcknowledgedHipaaNotice: false,
  };

export const qualifyingQuestionsSectionDefaultValues: QualifyingQuestionsSection =
  {
    diagnoses: {
      hasType1Diabetes: false,
      hasType2Diabetes: false,
      hasHighBloodPressure: false,
      hasHighCholesterol: false,
      hasHeartDisease: false,
      isObese: false,
      hasOther: "",
      noneOfTheAbove: false,
    },
    isTobaccoUser: false,
    hasAppliedForFinancialAssistance: false,
    hasHealthConditionCausedByTobaccoUse: false,
    hasHealthInsurance: false,
    hasCloseFamilyHistoryOfProstateCancer: false,
  };

export const programSelectionSectionDefaultValues: ProgramSelectionSection = {
  optedInToHealthyHabits: false,
  optedInToDiabetesPrevention: false,
  optedInToRigsWithoutCigs: false,
  optedInToVaccineVoucher: false,
  optedInToGetPreventativeScreenings: false,
};

export const programSpecificQuestionsSectionDefaultValues: ProgramSpecificQuestionsSection =
  {
    hasOptedInToHealthyHabits: false,
    hasOptedInToDiabetesPrevention: false,
    hasOptedInToRigsWithoutCigs: false,
    hasOptedInToVaccineVoucher: false,
    hasOptedInToGetPreventativeScreenings: false,
    healthyHabitsAndDiabetesPrevention: {
      weight: 0,
      heightFeet: 0,
      heightInches: 0,
      bmi: 0,
      hasHadGlucoseOrA1CTestInPastYear: false,
      glucoseOrA1CTestResult: "",
      systolicBloodPressure: 0,
      diastolicBloodPressure: 0,
      movementAndActivityRanking: "1",
      energyRanking: "1",
      sleepRanking: "1",
      emotionalHealthRanking: "1",
      waterBottlesPerDay: "1",
      fruitAndVegetableServingsPerDay: "0",
      otherIllnessOrInjury: "",
      biggestHealthyLivingChallenge: "",
      shortTermHealthGoals: "",
      longTermHealthGoals: "",
      devices: {
        hasScale: false,
        hasBloodPressureCuff: false,
        hasGlucoseMonitor: false,
        hasA1cHomeTest: false,
        hasFitnessTracker: false,
        hasBodyTapeMeasure: false,
        hasResistanceBands: false,
        hasOtherExerciseEquipment: false,
        noneOfTheAbove: false,
      },
      healthyHabitsHopefulLearnings: "",
      diabetesPreventionHopefulLearnings: "",
    },
    rigsWithoutCigs: {
      tobaccoForm: {
        doesUseCigarettes: false,
        doesUseSmokelessTobacco: false,
      },
      tobaccoUsageLength: "",
      isFirstTimeTryingToQuit: false,
      methodsUsedToQuit: {
        hasNotTriedToQuit: false,
        hasTriedColdTurkey: false,
        hasUsedAudiobook: false,
        hasUsedChantix: false,
        hasUsedColdTurkey: false,
        hasUsedECigarettes: false,
        hasUsedGrindsCoffeePouches: false,
        hasUsedGum: false,
        hasUsedHypnosis: false,
        hasUsedLozenges: false,
        hasUsedMedication: false,
        hasUsedMobileApp: false,
        hasUsedNicotinePatch: false,
        hasUsedOther: false,
        hasUsedTaperMethod: false,
        hasUsedVarenicline: false,
        hasUsedWellbutrin: false,
      },
      tobaccoFagerstromScore: 0,
      firstTobaccoTime: "After 60 minutes",
      swallowTobaccoJuice: "Never",
      tobaccoHateToGiveUp: "All others",
      tobaccoCansPerWeek: "1",
      tobaccoChewMoreAfterAwakening: false,
      tobaccoChewWhenIll: false,
      cigaretteFagerstromScore: 0,
      firstSmokeTime: "After 60 minutes",
      isDifficultToNotSmokeInForbiddenAreas: false,
      cigaretteHateToGiveUp: "All others",
      cigarettesPerDay: "10 or less",
      smokeMoreInMorning: false,
      smokeWhenIll: false,
      plansToJoinFacebookGroup: false,
      whyDoYouWantToQuitSmoking: "",
      howCanWeHelpYou: "",
      referralSource: "Website",
      accountabilityPerson: {
        firstName: "",
        lastName: "",
        phoneNumber: "",
        relationshipToAccountabilityPerson: "Friend",
      },
      currentlyHasPrimaryCarePhysician: false,
    },
    vaccineVoucher: {
      vaccines: {
        wantsFluVaccine: false,
        wantsPneumoniaVaccine: false,
        wantsShinglesVaccine: false,
        wantsCovid19Vaccine: false,
      },
      voucherLocation: "Walgreens",
      additionalQuestions: "",
    },
    getPreventativeScreenings: {
      agreeToShareResults: false,
      prostateScreening: {
        agreeToGetAccountRegistered: false,
        agreesToProstateScreening: false,
        isNotApplicable: false,
        additionalQuestions: "",
      },
    },
  };
