name: Weekly Zoom Reminder
on:
  schedule:
    # Runs at 12:00 PM UTC (noon) every Sunday
    - cron: "0 12 * * 0"

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Send Zoom Reminder Emails
        run: |
          curl -X POST \
          ${{ secrets.ZOOM_REMINDER_API_URL}} \
          -H "x-api-key: ${{ secrets.API_KEY }}" \
          -H "Content-Type: application/json"
